# https://github.com/cowrie/cowrie
services:
  cowrie:
    image: cowrie/cowrie
    volumes:
      - ./session-logs:/cowrie/cowrie-git/var/lib/cowrie/tty/
      - ./user-files:/cowrie/cowrie-git/var/lib/cowrie/downloads/
      - ./cowrie/cowrie.json:/cowrie/cowrie-git/var/log/cowrie/cowrie.json
      - ./cowrie/cowrie.log:/cowrie/cowrie-git/var/log/cowrie/cowrie.log
      - ./motd:/cowrie/cowrie-git/honeyfs/etc/motd
      - ./cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
    ports:
      - 2222:2222
      - 2223:2223
