version: '3.8'

services:
  dionaea:
    image: dinotools/dionaea
    restart: always
    ports:
      - "21:21"
      - "42:42"
      - "69:69/udp"
      - "80:80"
      - "135:135"
      - "443:443"
      - "445:445"
      - "1433:1433"
      - "1723:1723"
      - "1883:1883"
      - "1900:1900/udp"
      - "3306:3306"
      - "5060:5060"
      - "5060:5060/udp"
      - "5061:5061"
      - "11211:11211"
    volumes:
      - ./dionaea-config:/opt/dionaea/etc
      - ./dionaea-data:/opt/dionaea/var/lib
      - ./dionaea-logs:/opt/dionaea/var/log

# volumes:
#   dionaea-config:
#   dionaea-data:
#   dionaea-logs:
